package exception;
import java.util.Scanner;
public class tcf {
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		try {
			Scanner sc =new Scanner(System.in);
			System.out.println("enter the numerator:");
			int num=sc.nextInt();
			System.out.println("enter the denominator:");
			int deno=sc.nextInt();
			int res=num/deno;
			System.out.println(res);
		}
		catch(Exception e) {
			System.out.println("exception handled");
		}
		finally {
			System.out.println("inside finally block");
		}
	}
}
........................................
enter the numerator:
5
enter the denominator:
6
0
inside finally block
